### ISSUE TITLE
[Feature] Add Unique Prime Number Calculator

### ISSUE THREAD

**Issue by debangi29** [Rakesh9100/CalcDiverse#1095]
### Description

A "unique prime" is a prime number that remains prime when any single digit is removed from it. 
I can add an unique prime number calculator 
1. It can tell if a number is an unique prime number or not
2. It can print all the unique prime numbers in a given range

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls complete your assigned issues @debangi29

**Comment by bharat-c27** [comment]
Hello @Rakesh9100, I would love to contribute to the issue.
Can you please assign me this issue, so that I can start working on this.

As per my understanding I have mentioned 2 examples, please correct me if I am wrong.

**23** is a prime number.
Removing the digit '2' gives 3, which is prime.
Removing the digit '3' gives 2, which is prime.
Since removing any digit results in a prime number, **23 is a unique prime**.

**97** is a prime number.
Removing the digit '9' gives 7, which is prime.
However, removing the digit '7' gives 9, which is not prime.
Therefore, 97 is **not a unique prime**.

**Comment by jessicachawla** [comment]
@Rakesh9100  this issue can be assigned. 
@bharat-c27 just and fyi it's for greater than 99 as well. 
202 is not a unique as when we remove 0 it will become 22. So any of the three numbers can be removed and then consider. Similarly for 4 digit, 5 digit numbers and so on

**Comment by bharat-c27** [comment]
Okay sure !!

**Comment by Rakesh9100** [comment]
Go ahead @bharat-c27

**Comment by bharat-c27** [comment]
Sure @Rakesh9100, I will start working on this right now onwards.
But I want to request you to assign the issue #1317 to me, because I am done with coding part. Once you assign me the issue I will raise the PR for that.

Thank you!!
