### ISSUE TITLE
[Feature] Adding QR Code Calculator

### ISSUE THREAD

**Issue by Sakshamjain98** [Rakesh9100/CalcDiverse#457]
### Description

i want to add a calculator that calculates the qr code for any text

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Sakshamjain98** [comment]
Sir please assign me this issue under iwoc

**Comment by Rakesh9100** [comment]
Proceed @Sakshamjain98

**Comment by Rakesh9100** [comment]
Status of your PR @Sakshamjain98

**Comment by AftabMankapure** [comment]
Assign me under JWOC

**Comment by Rakesh9100** [comment]
Proceed @AftabMankapure

**Comment by AftabMankapure** [comment]
![QR](https://github.com/Rakesh9100/CalcDiverse/assets/125949765/97a8e46a-7b89-44b0-9abe-d2693abc91e5)
It is ok

**Comment by Rakesh9100** [comment]
Looks fine @AftabMankapure

**Comment by SohanRC** [comment]
@AftabMankapure Heyyy !! This is my exact project in which I have already submitted a PR in FunFusion !! Why are copying others project in submitting a PR for yourself ??

@Rakesh9100  Please look into this !!

**Comment by AftabMankapure** [comment]
I will check

**Comment by Rakesh9100** [comment]
Why are you copying the code from one repository and pasting in another repo just for the points. If you are unable to solve issue by your own approach, then just don't ask for assigning an issue to you. Open Source is for learning and contributing rather than engaging in practices resembling plagiarism.

If found indulging in such activity again, you will be terminated from the open source program and will not be allowed to participate further!! @AftabMankapure

**Comment by Rakesh9100** [comment]
If you want you can takeover this issue and complete it @SohanRC

**Comment by SohanRC** [comment]
> If you want you can takeover this issue and complete it @SohanRC

Yes , assign me . I Would like to complete it

**Comment by Rakesh9100** [comment]
Proceed @SohanRC

**Comment by Rakesh9100** [comment]
You can report anytime to me or to the organizers if found any malpractices @SohanRC

**Comment by SohanRC** [comment]
> Proceed @SohanRC

Thank You for assigning

**Comment by SohanRC** [comment]
> You can report anytime to me or to the organizers if found any malpractices @SohanRC

Okk

**Comment by AftabMankapure** [comment]
@Rakesh9100  sorry for that issue
@SohanRC  bro you just check the output or both code (your and my) it same i agree with that 
but before pointing any claim you need to check complete code
means other file js, html, css 
this is index page you can find difference in button section ( ### logic chek kar ) because it just 3 line code you can find only one line change  
![QR index](https://github.com/Rakesh9100/CalcDiverse/assets/125949765/2c4366ed-5ef4-4e35-ad8d-f40feb14632d)

this is script file  you can also check this 
![QR_Script](https://github.com/Rakesh9100/CalcDiverse/assets/125949765/060cac61-b610-4b2d-bba5-a7e9456de60b)

and 
about css file it is same because i use chat gbt for style the simple webpage just by providing the simple property 
i.e. background color   
![css1](https://github.com/Rakesh9100/CalcDiverse/assets/125949765/c73983cc-2ce3-4def-b09b-801de1a31e4e)
  
![css2](https://github.com/Rakesh9100/CalcDiverse/assets/125949765/02fecf51-6d79-426d-a10b-4a51c3d8fc89)
and also i use this site  https://cssgradient.io/ to find proper css using different image  @SohanRC  bro pls check the all file @Rakesh9100  i close this PR #576   because this is my first OSC

**Comment by SohanRC** [comment]
@AftabMankapure Bro you have just added that onclick function rather than incorporating the same logic in js file ? Just writing that does not change anything right ? Can you please explain how each and everything in my code and your code is same except that inline onclick() function? Even the variables are same too ? This cannot be a coincidence right ?

**Comment by Rakesh9100** [comment]
@AftabMankapure @SohanRC Maintain the decorum of the open source without making any further discussions!!

**Comment by SohanRC** [comment]
@AftabMankapure Even most of the CSS is also same except the last part where you have added some animation !!

**Comment by SohanRC** [comment]
> @AftabMankapure @SohanRC Maintain the decorum of the open source without making any further discussions!!

OKK
