### ISSUE TITLE
[Style] Change the font-family of logo

### ISSUE THREAD

**Issue by binary-amigo** [Rakesh9100/CalcDiverse#621]
### What's the style idea?

We need to improve the font family cause its not that pretty

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a IWOC'24 contributor.
- [x] I am a JWOC'24 contributor.
- [x] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Manishar55** [comment]
@Rakesh9100 please assign this issue to me

**Comment by udita-0707** [comment]
Hi @Rakesh9100 ,

I hope this message finds you well. I'm reaching out to express my interest in contributing to the project and to request assignment of the issue titled "Change the font-family of logo and hero text from Ubuntu to Pacifico".

I've reviewed the issue description and I believe I can make a meaningful contribution to address it. 
Please let me know if this issue is available for assignment.

Looking forward to contributing to the project!

Best regards,
