### ISSUE TITLE
[Feature] Add shift operations in Bitwise Calculator

### ISSUE THREAD

**Issue by sanikaahadap** [Rakesh9100/CalcDiverse#648]
### Description

Sir, I have relevant knowledge about bitwise operations and concerned programming capabilities. I request you to assign this task to me. 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Bitwise Calculator is already present on the website, so for what bug you have opened this issue @sanikaahadap

**Comment by sanikaahadap** [comment]
The bitwise calculator has inconsistencies and some cases aren't being handled properly, which is leading to incorrect results, which is why I had opened the issue.

**Comment by Uday2902** [comment]
Hi @Rakesh9100, i think there is an issue with bitwise NOT operation it is currently calculated using this formula : 
![image](https://github.com/Rakesh9100/CalcDiverse/assets/127274394/7b019cfa-ce7e-46df-883b-3b0e8a615639)


But "~" operator gives output in 2's complement so current output is : 
![image](https://github.com/Rakesh9100/CalcDiverse/assets/127274394/b55b982b-55a3-407e-af45-f4a9c902de2f)


Output should be : "010010" instead of "-101110"

Correct formula to calculate NOT is : 
![image](https://github.com/Rakesh9100/CalcDiverse/assets/127274394/959031ed-a5b8-40eb-926a-2b6c98e3e8e9)


I would like to work on this issue and i would also like to add two more fundamental bitwise operations :

1) Bitwise Left-shift
2) Bitwise Right-shift

I request you to assign this issue to me.

**Comment by Rakesh9100** [comment]
Provide the supporting screenshots of the issues @sanikaahadap

**Comment by Rakesh9100** [comment]
You can go ahead @Uday2902
